/**
 * Postgres access behind a tiny interface, with two engines:
 *  - a real server (Supabase, Neon, Vercel Postgres) when DATABASE_URL / POSTGRES_URL is set,
 *  - PGlite (Postgres compiled to WebAssembly) in-process otherwise — local dev and tests,
 *    nothing to install.
 *
 * Every table lives in the `crm` schema, so the CRM can share a database with another app.
 */
import fs from 'node:fs';
import path from 'node:path';

export type Row = Record<string, any>;

export interface Q {
  all<T = Row>(sql: string, params?: unknown[]): Promise<T[]>;
  get<T = Row>(sql: string, params?: unknown[]): Promise<T | undefined>;
  /** Returns the number of affected rows. */
  run(sql: string, params?: unknown[]): Promise<number>;
}

export interface DB extends Q {
  tx<T>(fn: (q: Q) => Promise<T>): Promise<T>;
  exec(sql: string): Promise<void>;
  close(): Promise<void>;
}

/** `?` placeholders → `$1, $2 …` (none of our SQL has a literal ? inside quotes). */
function pg(sql: string): string {
  let n = 0;
  return sql.replace(/\?/g, () => `$${++n}`);
}

const SCHEMA = `
CREATE SCHEMA IF NOT EXISTS crm;

CREATE TABLE IF NOT EXISTS crm.segments (
  name        TEXT PRIMARY KEY,
  weight      DOUBLE PRECISION NOT NULL DEFAULT 1,
  goal        TEXT NOT NULL DEFAULT '',
  who         TEXT NOT NULL DEFAULT '',
  opening     TEXT NOT NULL DEFAULT '',
  hook        TEXT NOT NULL DEFAULT '',
  offer       TEXT NOT NULL DEFAULT '',
  cta         TEXT NOT NULL DEFAULT '',
  objections  TEXT NOT NULL DEFAULT '',
  why         TEXT NOT NULL DEFAULT '',
  sort        INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS crm.templates (
  code      TEXT PRIMARY KEY,
  kind      TEXT NOT NULL DEFAULT '',
  segments  TEXT NOT NULL DEFAULT '',
  subject   TEXT NOT NULL DEFAULT '',
  body      TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS crm.leads (
  id           TEXT PRIMARY KEY,
  segment      TEXT NOT NULL DEFAULT 'NIEZNANA',
  company      TEXT NOT NULL,
  company_key  TEXT NOT NULL,
  industry     TEXT NOT NULL DEFAULT '',
  city         TEXT NOT NULL DEFAULT '',
  phone        TEXT NOT NULL DEFAULT '',
  email        TEXT NOT NULL DEFAULT '',
  web          TEXT NOT NULL DEFAULT '',
  person       TEXT NOT NULL DEFAULT '',
  stage        TEXT NOT NULL DEFAULT 'new',
  notes        TEXT NOT NULL DEFAULT '',
  extra        TEXT NOT NULL DEFAULT '',
  source       TEXT NOT NULL DEFAULT '',
  legacy_last_contact TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS leads_key   ON crm.leads(company_key);
CREATE INDEX IF NOT EXISTS leads_stage ON crm.leads(stage);

-- The one source of truth for what happened and what is planned.
-- Last/next contact on a lead are derived from here, never stored twice.
CREATE TABLE IF NOT EXISTS crm.activities (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id     TEXT NOT NULL REFERENCES crm.leads(id) ON DELETE CASCADE,
  date        TEXT NOT NULL,
  type        TEXT NOT NULL,
  note        TEXT NOT NULL DEFAULT '',
  owner       TEXT NOT NULL DEFAULT '',
  result      TEXT NOT NULL,
  stage_from  TEXT NOT NULL DEFAULT '',
  stage_to    TEXT NOT NULL DEFAULT '',
  legacy_id   TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS act_lead   ON crm.activities(lead_id, result, date);
CREATE INDEX IF NOT EXISTS act_result ON crm.activities(result, date);
CREATE INDEX IF NOT EXISTS act_date   ON crm.activities(date);

CREATE TABLE IF NOT EXISTS crm.events (
  id          TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'Other',
  date        TEXT NOT NULL,
  time        TEXT NOT NULL DEFAULT '',
  lead_id     TEXT NOT NULL DEFAULT '',
  company     TEXT NOT NULL DEFAULT '',
  location    TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'planned',
  owner       TEXT NOT NULL DEFAULT '',
  cost        TEXT NOT NULL DEFAULT '',
  notes       TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS crm.tasks (
  id         TEXT PRIMARY KEY,
  event_id   TEXT NOT NULL DEFAULT '',
  task       TEXT NOT NULL,
  owner      TEXT NOT NULL DEFAULT '',
  due        TEXT NOT NULL DEFAULT '',
  status     TEXT NOT NULL DEFAULT 'todo',
  notes      TEXT NOT NULL DEFAULT '',
  completed  TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS tasks_event ON crm.tasks(event_id);
-- tasks can belong to an event (project), a company, or nothing; they carry ready-made
-- materials (JSON [{title, body}]) and knowledge files (comma-separated ids)
ALTER TABLE crm.tasks ADD COLUMN IF NOT EXISTS lead_id TEXT NOT NULL DEFAULT '';
ALTER TABLE crm.tasks ADD COLUMN IF NOT EXISTS materials TEXT NOT NULL DEFAULT '';
ALTER TABLE crm.tasks ADD COLUMN IF NOT EXISTS attachments TEXT NOT NULL DEFAULT '';
ALTER TABLE crm.tasks ADD COLUMN IF NOT EXISTS sort INTEGER NOT NULL DEFAULT 0;
ALTER TABLE crm.tasks ADD COLUMN IF NOT EXISTS person_id BIGINT NOT NULL DEFAULT 0;

-- Studio: pages, presentations and email templates made with the assistant, with their versions and chat.
CREATE TABLE IF NOT EXISTS crm.designs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  kind          TEXT NOT NULL DEFAULT 'www',
  versions      TEXT NOT NULL DEFAULT '[]',
  chat          TEXT NOT NULL DEFAULT '[]',
  container_id  TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

-- Small key/value settings: writing styles, project instructions.
CREATE TABLE IF NOT EXISTS crm.settings (
  key    TEXT PRIMARY KEY,
  value  TEXT NOT NULL DEFAULT ''
);

-- People the user works with (director, colleagues, teachers): who a task or an email is for.
CREATE TABLE IF NOT EXISTS crm.people (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT '',
  email         TEXT NOT NULL DEFAULT '',
  phone         TEXT NOT NULL DEFAULT '',
  aliases       TEXT NOT NULL DEFAULT '',
  notes         TEXT NOT NULL DEFAULT '',
  contacts      INTEGER NOT NULL DEFAULT 0,
  last_contact  TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL
);

-- Knowledge base: files and notes the assistant can search and attach.
CREATE TABLE IF NOT EXISTS crm.knowledge (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        TEXT NOT NULL,
  filename     TEXT NOT NULL DEFAULT '',
  mime         TEXT NOT NULL DEFAULT '',
  size         INTEGER NOT NULL DEFAULT 0,
  content      BYTEA,
  text         TEXT NOT NULL DEFAULT '',
  description  TEXT NOT NULL DEFAULT '',
  tags         TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL
);
ALTER TABLE crm.knowledge ADD COLUMN IF NOT EXISTS anthropic_file_id TEXT NOT NULL DEFAULT '';

-- One row per email sent from the CRM, so a campaign is never sent twice to the same address.
CREATE TABLE IF NOT EXISTS crm.sends (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign    TEXT NOT NULL,
  lead_id     TEXT NOT NULL DEFAULT '',
  email       TEXT NOT NULL,
  subject     TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL,
  error       TEXT NOT NULL DEFAULT '',
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS sends_campaign ON crm.sends(campaign, email);
`;

/* ------------------------------------------------------------ server Postgres */

/**
 * Connection strings from Supabase and Neon carry libpq-only options (sslmode,
 * channel_binding, supa, pgbouncer) that postgres.js would forward to the server
 * as settings — and the server rejects them. SSL is configured explicitly instead.
 */
export function cleanUrl(url: string): string {
  const u = new URL(url);
  for (const k of ['sslmode', 'channel_binding', 'supa', 'pgbouncer', 'sslrootcert', 'options']) u.searchParams.delete(k);
  return u.toString();
}

async function openRemote(url: string): Promise<DB> {
  const { default: postgres } = await import('postgres');
  const local = /localhost|127\.0\.0\.1/.test(url);
  const sql = postgres(cleanUrl(url), {
    prepare: false,                        // required by Supabase / Neon poolers (transaction mode)
    ssl: local ? false : 'require',
    max: 5,
    idle_timeout: 20,
    onnotice: () => {},
  });
  const make = (s: any): Q => ({
    all: async (q, p = []) => (await s.unsafe(pg(q), p as any[])) as any[],
    get: async (q, p = []) => ((await s.unsafe(pg(q), p as any[])) as any[])[0],
    run: async (q, p = []) => Number((await s.unsafe(pg(q), p as any[])).count) || 0,
  });
  return {
    ...make(sql),
    tx: (fn) => sql.begin((t: any) => fn(make(t))) as any,
    exec: async (q) => { await sql.unsafe(q); },
    close: () => sql.end(),
  };
}

/* ------------------------------------------------------------ embedded PGlite */

async function openEmbedded(dir: string): Promise<DB> {
  const { PGlite } = await import('@electric-sql/pglite');
  if (dir !== 'memory://') fs.mkdirSync(path.dirname(dir), { recursive: true });
  const db = new PGlite(dir === 'memory://' ? undefined : dir);
  const make = (s: any): Q => ({
    all: async (q, p = []) => (await s.query(pg(q), p)).rows,
    get: async (q, p = []) => (await s.query(pg(q), p)).rows[0],
    run: async (q, p = []) => (await s.query(pg(q), p)).affectedRows ?? 0,
  });
  return {
    ...make(db),
    tx: (fn) => db.transaction((t: any) => fn(make(t))),
    exec: async (q) => { await db.exec(q); },
    close: () => db.close(),
  };
}

export function databaseUrl(): string {
  return process.env.DATABASE_URL || process.env.POSTGRES_URL || process.env.SUPABASE_DB_URL || '';
}

/** Opens the database and makes sure the tables exist. */
export async function openDb(target = databaseUrl() || process.env.PGLITE_DIR || path.resolve('data/pglite')): Promise<DB> {
  if (process.env.VERCEL && !/^postgres/.test(target)) {
    throw new Error('Baza danych nie jest podłączona. W Vercel: Storage → Create Database (Neon albo Supabase) → Connect, ' +
      'albo dodaj zmienną DATABASE_URL. Potem Redeploy.');
  }
  const db = /^postgres(ql)?:\/\//.test(target) ? await openRemote(target) : await openEmbedded(target);
  await db.exec(SCHEMA);
  return db;
}

/** Insert many rows with few round trips — matters a lot over the network. */
export async function insertMany(q: Q, table: string, cols: string[], rows: unknown[][], chunk = 400) {
  for (let i = 0; i < rows.length; i += chunk) {
    const part = rows.slice(i, i + chunk);
    const values = part.map(() => `(${cols.map(() => '?').join(', ')})`).join(', ');
    await q.run(`INSERT INTO ${table} (${cols.join(', ')}) VALUES ${values}`, part.flat());
  }
}

export function nowIso(): string {
  return new Date().toISOString();
}
